name: Tests and code coverage

on:
  push:
    branches:
    - feature/*
    - cicd

jobs:
  install:
    name: Install Tools
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7'
      - name: Install Fastlane
        run: |
          gem install fastlane
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'    
  test_iOS:
    needs: install 
    name: iOS Tests
    runs-on: macos-latest
    timeout-minutes: 60
    env: 
      DEVELOPER_DIR: /Applications/Xcode.app/Contents/Developer
      working-directory: ./builder
    strategy:
      matrix:
        destination: ["platform=iOS Simulator,OS=14.4,name=iPhone 12"]
        scheme:
            # - TealiumAttributionTests-iOS
            # - TealiumAutotrackingTests-iOS 
            # - TealiumCollectTests-iOS
            - TealiumCoreTests-iOS
            # - TealiumLifecycleTests-iOS
            # - TealiumLocationTests-iOS
            # - TealiumMediaTests-iOS
            # - TealiumRemoteCommandsTests-iOS
            # - TealiumTagManagementTests-iOS
            # - TealiumVisitorServiceTests-iOS
    steps:
      - uses: actions/checkout@v2
      - name: Test - "${{ matrix.scheme }}"
        # run: fastlane scan --scheme "${{ matrix.scheme }}" --output-style "raw" --xcargs "-quiet" --output_files "${{ matrix.scheme }}".html
        # run: fastlane scan --scheme "${{ matrix.scheme }}" --output_files "${{ matrix.scheme }}".html
        run: fastlane scan --scheme "${{ matrix.scheme }}" --code_coverage true --skip_build true --output_directory "test_output"
        # run: swift test --enable-test-discovery --enable-code-coverage
        working-directory: ${{env.working-directory}}
      # - name: Code Coverage - "${{ matrix.scheme }}"
        # run: fastlane scan --scheme "${{ matrix.scheme }}" --output-style "raw" --xcargs "-quiet" --output_files "${{ matrix.scheme }}".html
        # run: fastlane scan --scheme "${{ matrix.scheme }}" --output_files "${{ matrix.scheme }}".html
        # run: fastlane run xcov workspace:"" project:"tealium-swift.xcodeproj" scheme:"${{ matrix.scheme }}" output_directory:"test_output"
        # run: fastlane run xcov project:"tealium-swift.xcodeproj" scheme:"${{ matrix.scheme }}" output_directory:"test_output"
        # working-directory: ${{env.working-directory}}
      - name: Generate and Upload Code Coverage
        run: bash <(curl -s https://codecov.io/bash) && ls
        working-directory: ${{env.working-directory}}
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
      - name: Validate Code Coverage Percengage
        run: python coverage.py "${{secrets.CODECOV_API_URL}}" && exit <(echo $?)
        working-directory: ${{env.working-directory}}     
  # test_macOS:
  #   needs: install
  #   name: macOS Tests
  #   runs-on: macos-latest
  #   timeout-minutes: 60
  #   env: 
  #     DEVELOPER_DIR: /Applications/Xcode.app/Contents/Developer
  #     working-directory: ./builder
  #   strategy:
  #     matrix:
  #       destination: ["platform=macOS,arch=x86_64"]
  #       scheme: 
  #         - TealiumCoreTests-macOS
  #         - TealiumCollectTests-macOS
  #         - TealiumLifecycleTests-macOS
  #         - TealiumMediaTests-macOS
  #         - TealiumVisitorServiceTests-macOS
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Test - "${{ matrix.scheme }}"
  #       run: fastlane scan --scheme "${{ matrix.scheme }}" --code_coverage true --skip_build true output_directory:"test_output"
  #       working-directory: ${{env.working-directory}}
  #     - name: Generate and Upload Code Coverage
  #       run: bash <(curl -s https://codecov.io/bash)
  #       working-directory: ${{env.working-directory}}
  # test_tvOS:
  #   needs: install
  #   name: tvOS Tests
  #   runs-on: macos-latest
  #   timeout-minutes: 60
  #   env: 
  #     DEVELOPER_DIR: /Applications/Xcode.app/Contents/Developer
  #     working-directory: ./builder
  #   strategy:
  #     matrix:
  #       destination: ["platform=tvOS Simulator,name=Apple TV"]
  #       scheme: 
  #         - TealiumCoreTests-tvOS
  #         - TealiumCollectTests-tvOS
  #         - TealiumLifecycleTests-tvOS
  #         - TealiumMediaTests-tvOS
  #         - TealiumVisitorServiceTests-tvOS
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Test "${{ matrix.scheme }}"
  #       run: fastlane scan --scheme "${{ matrix.scheme }}" --code_coverage true --skip_build true output_directory:"test_output"
  #       working-directory: ${{env.working-directory}}
  #     - name: Generate and Upload Code Coverage
  #       run: bash <(curl -s https://codecov.io/bash)
  #       working-directory: ${{env.working-directory}}
